### home page 
GET http://localhost:3000/

### error page
GET http://localhost:3000/abc

### Register
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "mrlocpro125@gmail.com",
    "password": "abc123"
}

### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "mrlocpro125@gmail.com",
    "password": "abc123"
}
### Logout
DELETE http://localhost:3000/users/logout
Content-Type: application/json

{
    "refreshToken": "<refresh_token>"
}
### Refresh Token
POST http://localhost:3000/users/refresh-token
Content-Type: application/json

{
    "refreshToken": "<refresh_token>"
}

### Get List User
GET http://localhost:3000/users/lists
Authorization: Bearer "<access_token>"

