### home page 
GET http://localhost:3000/

### error page
GET http://localhost:3000/abc

### Register
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "mrlocpro125@gmail.com",
    "password": "abc123"
}

### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "mrlocpro125@gmail.com",
    "password": "abc123"
}
### Logout
DELETE http://localhost:3000/users/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc4MTExN2VhMjZiNjgxYjI0OWZjNmIiLCJpYXQiOjE2ODU1OTA4NTMsImV4cCI6MTcxNzE0ODQ1M30.YTXZS2t-j9FhCFp-2slNS9EMiVw3e65imkZBt_79Tqk"
}
### Refresh Token
POST http://localhost:3000/users/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc4MTExN2VhMjZiNjgxYjI0OWZjNmIiLCJpYXQiOjE2ODU1OTA4NTMsImV4cCI6MTcxNzE0ODQ1M30.YTXZS2t-j9FhCFp-2slNS9EMiVw3e65imkZBt_79Tqk"
}

### Get List User
GET http://localhost:3000/users/lists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc4MTExN2VhMjZiNjgxYjI0OWZjNmIiLCJpYXQiOjE2ODU1OTEwNDAsImV4cCI6MTY4NTU5MTEwMH0.1U5K16uyCAncGlpEgiP1-GVH4eH_k1tw826yyeEkuTc

